name: tickets_test_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  talker_bloc_logger: ^4.1.5
  talker_dio_logger: ^4.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
