name: tickets_test_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.0.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  talker_bloc_logger: ^4.1.5
  talker_dio_logger: ^4.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.4.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sf_pro/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/sf_pro/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/sf_pro/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/sf_pro/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/sf_pro/SFProDisplay-Light.ttf
          weight: 300

flutter_gen:
  output: lib/generated/flutter_gen
  assets:
    enabled: true
    outputs:
      class_name: Assets

  integrations:
    flutter_svg: true
